apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-api-rs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: image-api-rs
  template:
    metadata:
      labels:
        bb: image-api-rs
    spec:
      containers:
      - name: image-api-rs
        image: image-api-rs:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: image-api-rs-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: image-api-rs
  ports:
  - port: 8088
    targetPort: 8088

