apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-port
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web-port
  template:
    metadata:
      labels:
        bb: web-port
    spec:
      containers:
      - name: web-port
        image: web-port
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web-port-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  externalIPs:
    - 10.96.28.227
  selector:
    bb: web-port
  ports:
  - port: 8085
    targetPort: 8085

